# Generated by Django 3.1.2 on 2020-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='day_created',
            field=models.CharField(default='11:11:1111', max_length=12),
            preserve_default=False,
        ),
    ]
