# Generated by Django 3.1.2 on 2020-11-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routml_app', '0003_auto_20201103_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='date',
        ),
        migrations.AddField(
            model_name='url',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
